// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include <lwpb/lwpb.h>

#include "Message.pb.h"

// 'PulseMessage' field descriptors
const struct lwpb_field_desc lwpb_fields_pulsemessage[] = {
    {
        .number = 1,
        .opts.label = LWPB_REQUIRED,
        .opts.typ = LWPB_ENUM,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "type",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.int32 = 1,
#endif
    },
    {
        .number = 2,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_MESSAGE,
        .opts.flags = 0,
        .msg_desc = PulseMessageTrace,
#if LWPB_FIELD_NAMES
        .name = "trace",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
    {
        .number = 3,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_MESSAGE,
        .opts.flags = 0,
        .msg_desc = PulseMessageEvent,
#if LWPB_FIELD_NAMES
        .name = "event",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
    {
        .number = 4,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_MESSAGE,
        .opts.flags = 0,
        .msg_desc = PulseMessageSampleStream,
#if LWPB_FIELD_NAMES
        .name = "samples",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
};

// 'PulseMessageStream' field descriptors
const struct lwpb_field_desc lwpb_fields_pulsemessagestream[] = {
    {
        .number = 1,
        .opts.label = LWPB_REPEATED,
        .opts.typ = LWPB_MESSAGE,
        .opts.flags = 0,
        .msg_desc = PulseMessage,
#if LWPB_FIELD_NAMES
        .name = "message",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
    {
        .number = 2,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_STRING,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "sessionID",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.string.str = "",
#endif
    },
    {
        .number = 3,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_STRING,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "clientID",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.string.str = "",
#endif
    },
    {
        .number = 4,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_SINT32,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "timezoneOffset",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.int32 = 0,
#endif
    },
    {
        .number = 5,
        .opts.label = LWPB_OPTIONAL,
        .opts.typ = LWPB_STRING,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "timezoneAbbreviation",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.string.str = "",
#endif
    },
};

// Message descriptors
const struct lwpb_msg_desc lwpb_messages_[] = {
    {
        .num_fields = 4,
        .fields = lwpb_fields_pulsemessage,
#if LWPB_MESSAGE_NAMES
        .name = "PulseMessage",
#endif
    },
    {
        .num_fields = 5,
        .fields = lwpb_fields_pulsemessagestream,
#if LWPB_MESSAGE_NAMES
        .name = "PulseMessageStream",
#endif
    },
};

// Service descriptors
const struct lwpb_service_desc lwpb_services_[] = {
};

